### ISSUE TITLE
Not compiling

### ISSUE THREAD

**Issue by ElectroBoy404NotFound** [darshdudhia/DarshOS#2]
Hello! Electro here. I tried to compile it, but the following error came:
`kernel.cpp:3:10: fatal error: Kernel_Utils/sound.cpp: No such file or directory
    3 | #include "Kernel_Utils/sound.cpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.`

So... Did you like forget to upload sound.cpp? it does not exist!

**Comment by darshdudhia** [comment]
Did you clone it or download the source code.zip?

**Comment by darshdudhia** [comment]
Everything except the realeases is probably bugged and no i tried figuring out sound but it didnt work so i forgot to remove the #include

**Comment by ElectroBoy404NotFound** [comment]
Oh ok
